# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1bb033df79524bb17bb5e6c31a47950af2dd004602ed77828fc70bdfd4ecc9db9c4fefad63cba499f18d0344821e5fbfd9d58d214cdf5b937bd67359c60ed98

test:
  secret_key_base: c40155b446f30a5f707d1765186dfe23760c8afdd19a67a3920d6415ebabbcf0e1796cb7e591bb73e8c43a85c4378882e0f75a96e22ead6d5eda5b897f04054f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
